return {
    name = "Test Map",
    width = 10,
    height = 10,
    rows = {
        [1] = {
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
        },
        [2] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [3] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [4] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [5] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "goal",  color = "0x0000FF" },
            { type = "block", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [6] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [7] = {
            { type = "wall",   color = "0xFFFFFF" },
            { type = "empty",  color = "0x000000" },
            { type = "empty",  color = "0x000000" },
            { type = "empty",  color = "0x000000" },
            { type = "player", color = "0x00FF00" },
            { type = "empty",  color = "0x000000" },
            { type = "empty",  color = "0x000000" },
            { type = "empty",  color = "0x000000" },
            { type = "empty",  color = "0x000000" },
            { type = "wall",   color = "0xFFFFFF" },
        },
        [8] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [9] = {
            { type = "wall",  color = "0xFFFFFF" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "empty", color = "0x000000" },
            { type = "wall",  color = "0xFFFFFF" },
        },
        [10] = {
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
            { type = "wall", color = "0xFFFFFF" },
        }
    }
}
